version: '3'
services:
  db:
    image: 'postgres:9.6.3'
    ports:
      - '5432:5432'
  redis:
    image: redis:5
    ports:
      - '6379:6379'
  server:
    image: 'clue/json-server'
    ports:
      - '5000:80'
    volumes:
      - './server.json:/data/db.json'
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '15672:15672'
      - '5672:5672'
