apiVersion: v1
kind: Service
metadata:
  name: {{ include "API_boilerplate.fullname" . }}
  labels:
{{ include "API_boilerplate.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.appPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "API_boilerplate.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
