timestamp_job:
  cron: "* * * * *"
  class: "Cron::Timestamp"
  args:
    - "teste.txt"

api_job:
  cron: "* * * * *"
  class: "Cron::Api"
  args:
    - "http://localhost:5000"

date_job:
  cron: "* * * * *"
  class: "Cron::Date"
