development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: ''
  database: sidekiq

test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: ''
  database: sidekiq
